### ISSUE TITLE
npm listed as a dependency

### ISSUE THREAD

**Issue by donnd-t** [lopidio/jsonPlaceholderReplacer#1]
Why is npm listed as a dependency? Is there any reason for this? Can it be removed?

This dependency causes problem for me as npm 5.x has a transitive dependency on http-proxy-agent 2.0.0 which has a security vulnerability.

**Comment by lopidio** [comment]
No, there's no good reason for this.
I see your point.
[Consider it removed](https://github.com/lopidio/jsonPlaceholderReplacer/commit/84702aafb2e121ba78eccedb9aa6b12e27ed5adc)

**Comment by donnd-t** [comment]
Great! Thank you.
