### ISSUE TITLE
String values become integer values after replacement

### ISSUE THREAD

**Issue by rynkevich** [lopidio/jsonPlaceholderReplacer#18]
Having the following `template.json` file:
```
{
  "sampleProperty": "{{placeholder}}"
}
```
and the `substitutions.json` file:
```
{
  "placeholder": "123"
}
```
running jsonPlaceholderReplacer like this:
```
ts-node index.ts template.json substitutions.json
```
gives me the result:
```
{
  "sampleProperty": 123
}
```

Considering examples from README, and the statement that jsonPlaceholderReplacer keeps original variable types, which follows these examples, it appears to be an unexpected behavior.

Quickly written unit test for this case gives me red. Is there actually an error? If yes, I would like to provide a PR with a fix and some tests.

**Comment by lopidio** [comment]
Great.
Yes, I think it's an error.
Since you don't mind, please send a PR with the fix and its tests.

Thanks.

**Comment by rynkevich** [comment]
There's one thing I didn't take into account – it's replacing placeholders inside string context, e.g.

Before:
```
{
  "greeting": "hello {{someone}}!"
}
```

Variable map:
```
{
  "someone": "world"
}
```

After:
```
{
  "greeting": "hello world!"
}
```

I think that it is a very important one, so I've fixed current version to support this scenario added a test for it in PR https://github.com/lopidio/jsonPlaceholderReplacer/pull/20

**Comment by lopidio** [comment]
Thanks for the PR.

I realized there was something wrong and just [committed a fix](https://github.com/lopidio/jsonPlaceholderReplacer/commit/cfb97c051662f181216b8b546c22c2a3e4745fbd) which creates conflicts with PR #20 .

Please let me know if this commit fix the issue.
If it doesn't, I'd love to merge the PR with the conflicts solved.

Thanks.

**Comment by rynkevich** [comment]
Just applied your changes. Sadly, the test shows that it doesn't fix the problem.

The "should keep string numbers as string" test is redundant as this case is covered in "should keep original type of string values".
Anyway, I've merged your commit, kept your style changes and also adjusted my code to be consistent, so it's ready to be pulled.
