### ISSUE TITLE
Zero value is treated as false

### ISSUE THREAD

**Issue by nikhil-thakkar** [lopidio/jsonPlaceholderReplacer#5]
If the variable is having zero as the value, the placeholder is not replaced.

**Comment by lopidio** [comment]
Good catch!

**Comment by nikhil-thakkar** [comment]
Simple hack.
`if (value == 0) {
                    value = '0'
                }`

**Comment by nikhil-thakkar** [comment]
Thank you so much for quick fix. Appreciate it!!

**Comment by lopidio** [comment]
Actually, I'm checking like this: `if (value !== undefined)`
It's in the CI pipeline right now, should be available in npm in a few seconds.

Thanks for your collaboration.
